import { useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Minus, Plus, Trash2, Repeat, AlertTriangle, Search } from 'lucide-react'
import { useApp } from '../context/AppContext.jsx'
import { ARTICLES, ARTICLES_LIST } from '../data/dummyData.js'
import { dishPersons, fmtEUR, neededAmount, orderedAmount, purchasePriceOrdered } from '../utils/calc.js'

export default function PositionEditor() {
  const { courseId, dishId } = useParams()
  const { activeBuffet, setActiveBuffet, deliveryDate, hidePurchasePrices, user } = useApp()
  const nav = useNavigate()
  const isChef = user?.role === 'chef'
  if (!isChef) return <div className="mx-auto max-w-3xl px-6 py-20 text-center"><p className="text-neutral-400">Du hast keinen Zugriff auf diese Seite.</p><button onClick={()=>nav('/buffet/edit')} className="mt-4 rounded-md bg-gold px-4 py-2 text-sm font-semibold text-neutral-900">Zurück zum Buffet</button></div>
  const course=activeBuffet?.courses.find(c=>c.id===courseId)
  const dish=course?.dishes.find(d=>d.id===dishId)
  const [showAdd,setShowAdd]=useState(false); const [search,setSearch]=useState(''); const [swapForId,setSwapForId]=useState(null)
  if(!activeBuffet||!dish)return <div className="mx-auto max-w-3xl px-6 py-20 text-center"><p className="text-neutral-400">Gericht nicht gefunden.</p><button onClick={()=>nav('/buffet/edit')} className="mt-4 rounded-md bg-gold px-4 py-2 text-sm font-semibold text-neutral-900">Zurück</button></div>
  const persons=dishPersons(dish,activeBuffet.totalPersons)
  const totalGramm=dish.items.reduce((s,it)=>s+it.grammPerPerson,0)
  const update=mutator=>setActiveBuffet(prev=>{const next=JSON.parse(JSON.stringify(prev));const c=next.courses.find(x=>x.id===courseId);const d=c.dishes.find(x=>x.id===dishId);mutator(d,next);return next})
  const setGramm=(articleId,value)=>update(d=>{const it=d.items.find(i=>i.articleId===articleId);if(it)it.grammPerPerson=Math.max(0,Number(value)||0)})
  const incGramm=(articleId,delta)=>update(d=>{const it=d.items.find(i=>i.articleId===articleId);if(it)it.grammPerPerson=Math.max(0,(it.grammPerPerson||0)+delta)})
  const removeItem=articleId=>update(d=>{d.items=d.items.filter(i=>i.articleId!==articleId)})
  const addItem=article=>update(d=>{if(d.items.some(i=>i.articleId===article.id))return;d.items.push({articleId:article.id,grammPerPerson:50})})
  const swapItem=(oldId,newArticle)=>update(d=>{const it=d.items.find(i=>i.articleId===oldId);if(it)it.articleId=newArticle.id})
  const filteredArticles=useMemo(()=>{const s=search.toLowerCase().trim();if(!s)return ARTICLES_LIST.slice(0,12);return ARTICLES_LIST.filter(a=>a.name.toLowerCase().includes(s))},[search])
  return <div className="mx-auto max-w-[1400px] px-6 py-6 pb-16">
    <button onClick={()=>nav('/buffet/edit')} className="mb-4 inline-flex items-center gap-2 text-sm text-neutral-300 hover:text-gold"><ArrowLeft className="h-4 w-4"/> Zurück zum Buffet</button>
    <div className="mb-6 overflow-hidden rounded-xl border border-neutral-800 bg-neutral-950"><div className="flex flex-col items-stretch gap-0 md:flex-row"><img src={dish.image} alt="" className="h-48 w-full object-cover md:h-auto md:w-72"/><div className="flex-1 p-6"><div className="text-xs uppercase tracking-wider text-neutral-400">{course.name}</div><h1 className="mt-1 text-2xl font-bold">{dish.name}</h1><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Personen" value={persons}/><Stat label="Zutaten" value={dish.items.length}/><Stat label="Gramm/Person" value={`${totalGramm} g`}/>{!hidePurchasePrices&&<Stat label="EK (bestellt)" value={fmtEUR(dish.items.reduce((s,it)=>s+purchasePriceOrdered(it,persons),0))}/>}</div></div></div></div>
    <div className="overflow-hidden rounded-xl border border-neutral-800 bg-neutral-950">
      <div className="grid grid-cols-12 gap-3 border-b border-neutral-800 bg-neutral-900 px-4 py-3 text-[10px] uppercase tracking-wider text-neutral-400"><div className="col-span-4">Artikel</div><div className="col-span-3">Grammatur / Person</div><div className="col-span-3">Bedarf / Gebinde</div><div className="col-span-1 text-right">Preis</div><div className="col-span-1 text-right">Aktionen</div></div>
      {dish.items.length===0&&<div className="px-4 py-10 text-center text-sm text-neutral-500">Keine Zutaten. Fügen Sie einen Artikel hinzu.</div>}
      {dish.items.map(it=>{const art=ARTICLES[it.articleId];if(!art)return null;const need=neededAmount(it,persons),ord=orderedAmount(it,persons),oh=ord-need,price=purchasePriceOrdered(it,persons),unavailable=art.unavailableOn?.includes(deliveryDate);return <div key={it.articleId} className="grid grid-cols-12 items-center gap-3 border-b border-neutral-800 px-4 py-4 last:border-b-0">
        <div className="col-span-4 flex items-center gap-3"><img src={art.image} className="h-12 w-12 rounded object-cover"/><div className="min-w-0"><div className="truncate text-sm font-medium text-white">{art.name}</div><div className="text-xs text-neutral-500">Gebinde: {art.gebinde} {art.unit}</div>{unavailable&&<div className="mt-1 inline-flex items-center gap-1 rounded bg-red-500/15 px-1.5 py-0.5 text-[10px] font-medium text-red-300"><AlertTriangle className="h-3 w-3"/> nicht lieferbar</div>}</div></div>
        <div className="col-span-3"><div className="inline-flex items-center rounded-md border border-neutral-700 bg-neutral-900"><button onClick={()=>incGramm(it.articleId,-5)} className="p-2 text-neutral-400 hover:text-gold"><Minus className="h-3.5 w-3.5"/></button><input type="number" min="0" value={it.grammPerPerson} onChange={e=>setGramm(it.articleId,e.target.value)} className="w-16 bg-transparent text-center text-sm outline-none"/><span className="pr-2 text-xs text-neutral-500">{art.unit}</span><button onClick={()=>incGramm(it.articleId,5)} className="p-2 text-neutral-400 hover:text-gold"><Plus className="h-3.5 w-3.5"/></button></div></div>
        <div className="col-span-3"><div className="text-sm text-neutral-200">{need} {art.unit} <span className="text-neutral-500">→ bestellt {ord} {art.unit}</span></div>{oh>0&&<div className="mt-0.5 text-xs text-amber-400">Überhang: +{oh} {art.unit}</div>}</div>
        <div className="col-span-1 text-right text-sm font-medium text-gold">{hidePurchasePrices?'—':fmtEUR(price)}</div>
        <div className="col-span-1 flex justify-end gap-1"><button onClick={()=>setSwapForId(it.articleId)} className="rounded-md border border-neutral-700 bg-neutral-900 p-2 text-neutral-300 hover:border-gold/60 hover:text-gold" title="Artikel austauschen"><Repeat className="h-4 w-4"/></button><button onClick={()=>removeItem(it.articleId)} className="rounded-md border border-neutral-700 bg-neutral-900 p-2 text-neutral-300 hover:border-red-500/60 hover:text-red-400" title="Artikel entfernen"><Trash2 className="h-4 w-4"/></button></div>
      </div>})}
    </div>
    <div className="mt-6">{!showAdd?<button onClick={()=>setShowAdd(true)} className="flex items-center gap-2 rounded-md border border-dashed border-neutral-700 bg-neutral-950 px-4 py-2.5 text-sm text-neutral-300 hover:border-gold/60 hover:text-gold"><Plus className="h-4 w-4"/> Artikel hinzufügen</button>:<ArticlePicker search={search} setSearch={setSearch} articles={filteredArticles} onPick={a=>{addItem(a);setShowAdd(false);setSearch('')}} onClose={()=>{setShowAdd(false);setSearch('')}} title="Artikel aus Katalog hinzufügen"/>}</div>
    {swapForId&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-xl border border-neutral-800 bg-neutral-950 p-5 shadow-2xl"><ArticlePicker search={search} setSearch={setSearch} articles={filteredArticles} onPick={a=>{swapItem(swapForId,a);setSwapForId(null);setSearch('')}} onClose={()=>{setSwapForId(null);setSearch('')}} title={`Artikel austauschen: ${ARTICLES[swapForId]?.name}`}/></div></div>}
  </div>
}
function Stat({label,value}){return <div className="rounded-md border border-neutral-800 bg-neutral-900 px-3 py-2"><div className="text-[10px] uppercase tracking-wider text-neutral-500">{label}</div><div className="text-sm font-semibold text-white">{value}</div></div>}
function ArticlePicker({search,setSearch,articles,onPick,onClose,title}){return <div className="rounded-lg border border-neutral-800 bg-neutral-950 p-4"><div className="mb-3 flex items-center justify-between"><div className="text-sm font-semibold">{title}</div><button onClick={onClose} className="text-xs text-neutral-400 hover:text-white">Schließen</button></div><div className="mb-3 flex items-center gap-2 rounded-md border border-neutral-700 bg-neutral-900 px-3 py-2"><Search className="h-4 w-4 text-neutral-500"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Artikel suchen…" className="w-full bg-transparent text-sm outline-none"/></div><div className="grid max-h-80 grid-cols-1 gap-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{articles.map(a=><button key={a.id} onClick={()=>onPick(a)} className="flex items-center gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-2 text-left hover:border-gold/60"><img src={a.image} className="h-10 w-10 rounded object-cover"/><div className="min-w-0 flex-1"><div className="truncate text-sm text-white">{a.name}</div><div className="text-xs text-neutral-500">{a.gebinde} {a.unit} / Gebinde</div></div><Plus className="h-4 w-4 text-gold"/></button>)}{articles.length===0&&<div className="col-span-full p-4 text-center text-xs text-neutral-500">Keine Treffer.</div>}</div></div>}
